const PRODUCTS = [
  { id:"CME-CL", benchmark:"WTI", exchange:"NYMEX / CME Group", kind:"future", code:"CL", name:"WTI Crude Oil futures", size:1000, settlement:"Physical", url:"https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.html" },
  { id:"CME-MCL", benchmark:"WTI", exchange:"NYMEX / CME Group", kind:"future", code:"MCL", name:"Micro WTI Crude Oil futures", size:100, settlement:"Financial", url:"https://www.cmegroup.com/markets/energy/crude-oil/micro-wti-crude-oil.html" },
  { id:"CME-LO", benchmark:"WTI", exchange:"NYMEX / CME Group", kind:"option", code:"LO", name:"WTI Crude Oil options", size:1000, settlement:"Exercises into CL futures", url:"https://www.cmegroup.com/markets/energy/crude-oil/light-sweet-crude.contractSpecs.options.html" },
  { id:"CME-MCO", benchmark:"WTI", exchange:"NYMEX / CME Group", kind:"option", code:"MCO", name:"Micro WTI Crude Oil options", size:100, settlement:"Financial", url:"https://www.cmegroup.com/articles/faqs/micro-wti-crude-oil-options-faq.html" },
  { id:"ICE-B", benchmark:"Brent", exchange:"ICE Futures Europe", kind:"future", code:"B", name:"Brent Crude Futures", size:1000, settlement:"EFP delivery; cash-settlement option", url:"https://www.ice.com/products/219/Brent-Crude-Futures" },
  { id:"CME-BZ", benchmark:"Brent", exchange:"NYMEX / CME Group", kind:"future", code:"BZ", name:"Brent Last Day Financial Futures", size:1000, settlement:"Financial", url:"https://www.cmegroup.com/markets/energy/crude-oil/brent-crude-oil-last-day.html" },
  { id:"CME-BE", benchmark:"Brent", exchange:"NYMEX / CME Group", kind:"option", code:"BE", name:"Brent Crude options", size:1000, settlement:"Exercises into BZ futures", url:"https://www.cmegroup.com/markets/energy/energy-options.html" },
];
const bounded=(value,min,max,fallback)=>{const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;};
export default async function handler(request,response){
  const input=request.method==="POST"?request.body||{}:request.query||{};const benchmark=String(input.benchmark||"Brent").toUpperCase()==="WTI"?"WTI":"Brent";const volume=bounded(input.volume,1,1e9,300000),coverage=bounded(input.coverage,0,100,60)/100,futuresShare=bounded(input.futuresShare,0,100,70)/100;const matched=PRODUCTS.filter((item)=>item.benchmark===benchmark).map((item)=>{const target=item.kind==="future"?volume*coverage*futuresShare:volume*coverage*(1-futuresShare);const contracts=Math.round(target/item.size);return{...item,contracts,coveredBarrels:contracts*item.size,roundingError:contracts*item.size-target,verification:"Exchange product specification"};});
  let broker={connected:false,name:"IBKR",message:"Configure IBKR_API_BASE_URL and an authenticated brokerage session to resolve tradable expiries and live quotes. No order is submitted by this service."};
  if(process.env.IBKR_API_BASE_URL){broker={...broker,connected:true,message:"Broker adapter configured. Contract discovery still requires an authenticated IBKR session; order submission remains disabled."};}
  response.setHeader("Cache-Control","public, s-maxage=3600, stale-while-revalidate=86400");response.status(200).json({asOf:new Date().toISOString(),benchmark,products:matched,broker,executionEnabled:false,disclaimer:"Exchange-listed product matching and scenario analytics only. Prices, premiums and expiries must be verified with an authorized broker before execution."});
}
